# macro for 64Cu
#
/analysis/setFileName Cu64_simulation
#
/control/cout/ignoreThreadsExcept 0
/control/verbose 2
/run/verbose 1
#
# Set a very high time threshold to allow all decays to happen
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year
#
/gun/particle ion
/gun/ion 29 64 0 0
#
/rdecay01/fullChain false
#
/process/em/fluo true
/process/em/auger true
/process/em/pixe true
#
/run/setCut 1 um
#/run/printProgress 1
/rdecay01/fullChain false
/run/beamOn 100
