
# Inizializzazione
/run/initialize

# Configurazione Visualizzatore
/vis/open OGL 600x600-0+0
/vis/drawVolume
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/set/style surface

# Visualizzazione Traiettorie (Base)
/tracking/storeTrajectory 1
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate

# Utilità e Pulizia
/vis/geometry/set/visibility World_Log 0 false
/vis/scene/add/axes 0 0 0 1 um
/vis/viewer/flush

/run/beamOn 10

# Opzionale: colora le traiettorie in base alla carica (molto utile!)
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true