# Inizializzazione
/run/initialize

# --- Sorgente: Rame-64 ---
# --- Sorgente: Rame-64 distribuita nel volume ---
/gps/particle ion
/gps/ion 29 64 0 0

/gps/energy 0 eV

# Definisci la sorgente come volumetrica
/gps/pos/type Volume
/gps/pos/shape Sphere
/gps/pos/radius 10 um
/gps/pos/centre 0. 0. 0. um
/gps/pos/confine Physical_Nucleus

# Direzione isotropa
/gps/ang/type iso

# --- Lancio ---
/run/printProgress 5000
/run/beamOn 100000