# --- run.mac ---
# 0. Controllo
#/control/verbose 0
#/run/verbose 1
# 1. Inizializzazione
/run/initialize
# 2. Configurazione della sorgente
/gps/particle ion
/gps/ion 29 64 0 0  # Rame-64
/gps/energy 0 eV    # Il decadimento genera l'energia
/gps/pos/type Volume
/gps/pos/shape Sphere
/gps/pos/centre 0 0 0 um
/gps/pos/radius 2.5 um
/gps/pos/confine Nucleus_Phys 

# /gps/pos/radius 4.5 um
# /gps/pos/confine Cell_Phys 

/gps/ang/type iso
# 3. Lancio (senza vis attiva qui)
/run/printProgress 100
/run/beamOn 20000